import { siteContent } from "@/data/siteContent";

export const CAFE_GALLERY_ITEMS = [
  {
    id: 1,
    category: "INTERIOR",
    categoryName: "INTERIOR",
    propertyId: 1,
    propertyName: "Kennedia Cafe",
    isActive: true,
    media: {
      mediaId: 1,
      type: "IMAGE",
      url: siteContent.images.cafes.parisian.src,
      fileName: "Parisian Cafe Interior",
      alt: "Parisian Cafe Interior",
      width: null,
      height: null,
    },
  },
  {
    id: 2,
    category: "BREWS",
    categoryName: "BREWS",
    propertyId: 1,
    propertyName: "Kennedia Cafe",
    isActive: true,
    media: {
      mediaId: 2,
      type: "IMAGE",
      url: siteContent.images.cafes.minimalist.src,
      fileName: "Coffee Brew Bar",
      alt: "Coffee Brew Bar",
      width: null,
      height: null,
    },
  },
  {
    id: 3,
    category: "BAKERY",
    categoryName: "BAKERY",
    propertyId: 1,
    propertyName: "Kennedia Cafe",
    isActive: true,
    media: {
      mediaId: 3,
      type: "IMAGE",
      url: siteContent.images.cafes.bakery.src,
      fileName: "Artisan Bakery Counter",
      alt: "Artisan Bakery Counter",
      width: null,
      height: null,
    },
  },
  {
    id: 4,
    category: "EVENTS",
    categoryName: "EVENTS",
    propertyId: 1,
    propertyName: "Kennedia Cafe",
    isActive: true,
    media: {
      mediaId: 4,
      type: "IMAGE",
      url: siteContent.images.cafes.highTea.src,
      fileName: "High Tea Setup",
      alt: "High Tea Setup",
      width: null,
      height: null,
    },
  },
  {
    id: 5,
    category: "OUTDOOR",
    categoryName: "OUTDOOR",
    propertyId: 1,
    propertyName: "Kennedia Cafe",
    isActive: true,
    media: {
      mediaId: 5,
      type: "IMAGE",
      url: siteContent.images.cafes.garden.src,
      fileName: "Garden Terrace",
      alt: "Garden Terrace",
      width: null,
      height: null,
    },
  },
  {
    id: 6,
    category: "INTERIOR",
    categoryName: "INTERIOR",
    propertyId: 1,
    propertyName: "Kennedia Cafe",
    isActive: true,
    media: {
      mediaId: 6,
      type: "IMAGE",
      url: siteContent.images.cafes.library.src,
      fileName: "Library Corner",
      alt: "Library Corner",
      width: null,
      height: null,
    },
  },
  {
    id: 7,
    category: "BREWS",
    categoryName: "BREWS",
    propertyId: 1,
    propertyName: "Kennedia Cafe",
    isActive: true,
    media: {
      mediaId: 7,
      type: "IMAGE",
      url: siteContent.images.cafes.library.src,
      fileName: "Library Cafe",
      alt: "Library Cafe",
      width: null,
      height: null,
    },
  },
  {
    id: 8,
    category: "EVENTS",
    categoryName: "EVENTS",
    propertyId: 1,
    propertyName: "Kennedia Cafe",
    isActive: true,
    media: {
      mediaId: 8,
      type: "IMAGE",
      url: siteContent.images.cafes.garden.src,
      fileName: "Outdoor Event",
      alt: "Outdoor Event",
      width: null,
      height: null,
    },
  },
];

export const CAFE_GALLERY_MEDIA = CAFE_GALLERY_ITEMS.map((item) => item.media);
